version: '3.9'
networks:
  docker.0:
    #This interface should be defined as using null driver. Do not remove it.
    driver: null
    driver_opts:
      # opt com.docker.network.driver.mtu: "9000" # default "1500" change this its depend upon ur network switch
      parent: ens160
    ipam:
      config:
        - subnet: "10.10.0.0/24"
          ip_range: "10.10.0.192/27"
          gateway: "10.10.0.1"
  docker.0:
    #This is the interface which is used for containers networking
    name: docker.0
    driver: macvlan
    driver_opts:
      # opt com.docker.network.driver.mtu: "9000" # default "1500" change this its depend upon ur network switch
      parent: ens160
    ipam:
      config:
        - subnet: "10.10.0.0/24"
          ip_range: "10.10.0.192/27"
          gateway: "10.10.0.1"
  ### my tagged vlan interface
  docker.22:
    #This interface should be defined as using null driver. Do not remove it.
    driver: null
    driver_opts:
      # opt com.docker.network.driver.mtu: "9000" # default "1500"change this its depend upon ur network switch
      parent: ens160.22
    ipam:
      config:
        - subnet: "10.10.22.0/24"
          ip_range: "10.10.22.128/25"
          gateway: "10.10.22.1"
  docker.22:
    #This is the interface which is used for containers networking
    name: docker.22
    driver: macvlan
    driver_opts:
      # opt com.docker.network.driver.mtu: "9000" # default "1500" change this its depend upon ur network switch
      parent: ens160.22
    ipam:
      config:
        - subnet: "10.10.22.0/24"
          ip_range: "10.10.22.128/25"
          gateway: "10.10.22.1"

services:
  ############################  CRICITAL #######################
  # Docker Socket Proxy - Security Enchanced Proxy for Docker Socket
  socket-proxy:
    image: tecnativa/docker-socket-proxy:latest
    container_name: socket-proxy
    hostname: socket-proxy
    restart: always
    cpus: 0.2
    mem_limit: 16M
    mem_reservation: 8M
    networks:
      socket_proxy:
        ipv4_address: 192.168.91.254 # You can specify a static IP
    privileged: true
    ports:
      # - "127.0.0.1:2375:2375" # Port 2375 should only ever get exposed to the internal network. When possible use this line.
      # I use the next line instead, as I want portainer to manage multiple docker endpoints within my home network.
      - "2375:2375"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - /etc/localtime:/etc/localtime:ro
    environment:
      - LOG_LEVEL=info # debug,info,notice,warning,err,crit,alert,emerg
      ## Variables match the URL prefix (i.e. AUTH blocks access to /auth/* parts of the API, etc.).
      # 0 to revoke access.
      # 1 to grant access.
      ## Granted by Default
      - EVENTS=1
      - PING=1
      - VERSION=1
      ## Revoked by Default
      # Security critical
      - AUTH=0
      - SECRETS=0
      - POST=1 # Ouroboros
      # Not always needed
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1 # Traefik, portainer, etc.
      - DISTRIBUTION=0
      - EXEC=0
      - IMAGES=1 # Portainer
      - INFO=1 # Portainer
      - NETWORKS=1 # Portainer
      - NODES=0
      - PLUGINS=0
      - SERVICES=1 # Portainer
      - SESSION=0
      - SWARM=0
      - SYSTEM=0
      - TASKS=1 # Portaienr
      - VOLUMES=1 # Portainer