tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 ## TLS 1.2
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        ## Legacy names for the corresponding cipher suites with the correct _SHA256
        ## suffix, retained for backward compatibility.
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 #= TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305 #= TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
        - TLS_AES_256_GCM_SHA384 ## TLS 1.3
        - TLS_AES_128_GCM_SHA256 ## TLS 1.3
        - TLS_CHACHA20_POLY1305_SHA256 ## TLS 1.3
        ## TLS_FALLBACK_SCSV isn't a standard cipher suite but an indicator
        ## that the client is doing version fallback. See RFC 7507.
        - TLS_FALLBACK_SCSV
      curvePreferences:
        - CurveP521
        - CurveP384
      sniStrict: false

  ### Link to wildcard SSL
  certificates:
    - certFile: "/certs/local-cert.pem"
      keyFile: "/certs/local-key.pem"
      stores:
        - default
  ### And I am using this certificate as a default certificate, so traefik doest not genrate self sign certs

  stores:
    default:
      defaultCertificate:
        certFile: "/certs/local-cert.pem"
        keyFile: "/certs/local-key.pem"
